### PR TITLE
Refresh tests and add ForwardDiff example

### LINKED ISSUE #1: ForwardDiff compatibility
At the moment, autodiff of implicit functions relies on ChainRules, which means ForwardDiff won't work.

Suggested fix: manually overload the callable on ForwardDiff.Dual

### LINKED ISSUE #22: Typo in docs. `min` should be `argmin`
In: https://gdalle.github.io/ImplicitDifferentiation.jl/dev/examples/1_unconstrained_optimization/#
it says: image
I think `min` should be `argmin`

### PR DESCRIPTION
**Pull request by gdalle**
- ~~Adds Julia 1.6 compatibility and CI~~ the test with Convex.jl runs forever for reasons unknown
- Adds code formatting to tests
- Partially fixes #1 by showing how to use ForwardDiffChainRules.jl in the doc
- Fixes #22 by replacing min with argmin everywhere

### CODE REVIEW

**Comment by mohamed82008** [comment]
Nice PR! I will review it this weekend.

**Comment by gdalle** [comment]
Do you have any idea why the workflows terminate on Julia 1.8 and nightly but are still running after 4 hours on Julia 1.6? I haven't tried testing locally with 1.6 yet, will soon

**Comment by mohamed82008** [comment]
snape-no-idea-no-idea

**Comment by gdalle** [comment]
OK so the tests also run forever locally. I've tracked it down to example 2, where we solve a sparse linear regression with Convex.jl + SCS.jl. Gonna ask on Slack if anyone has a clue

**Review by mohamed82008 — APPROVED** [review]
Looks good!

**Pull request merged**
